uniphoto/admin/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask.views import MethodView
from flask_login import LoginManager, login_user, logout_user
from .models import AccountMapper

lm = LoginManager()
lm.login_view = 'auth.login'

mod = Blueprint('auth', __name__)


@lm.user_loader
def load_user(username):
    if username:
        mapper = AccountMapper()
        account = mapper.get(username)
        if account:
            return account
    return lm.anonymous_user


@mod.route('/logout')
def logout():
    logout_user()
    return redirect(url_for(lm.login_view))


#######################################################################################################################

from wtforms import Form
from wtforms.fields import HiddenField, PasswordField, TextField
from wtforms.validators import DataRequired


class LoginForm(Form):
    username = TextField("Login", validators=(DataRequired(),))
    password = PasswordField("Mot de passe", validators=(DataRequired(),))
    next = HiddenField()


#######################################################################################################################


class LoginView(MethodView):

    methods = ('GET', 'POST')

    def get(self):
        next = request.args.get('next', None)
        form = LoginForm(request.form, next=next)
        return render_template('login.html', next=next, form=form, skip_navigation=True)

    def post(self):
        form = LoginForm(request.form)
        mapper = AccountMapper()
        account = mapper.get(form.username.data)
        if account and account.verify_password(form.password.data):
            login_user(account)
            next = form.next.data or url_for('home')
            return redirect(next)
        else:
            flash("Login / mot de passe incorrect.", 'danger')
            return render_template('login.html', next=form.next.data, form=form, skip_navigation=True)


mod.add_url_rule('/login', view_func=LoginView.as_view('login'))

uniphoto/admin/views.py
from flask import abort, Blueprint, current_app, flash, redirect, render_template, request, url_for
from flask.views import MethodView
from ..models import *

mod = Blueprint('views', __name__)

#######################################################################################################################
from wtforms import Form
from wtforms.fields import TextAreaField, TextField
from wtforms.validators import DataRequired


class MetaForm(Form):
    title = TextField("Titre par défaut")
    description = TextAreaField("Description (SEO)")
    header = TextAreaField("En-tête (html)")
    footer = TextAreaField("Pied de page (html)")
    tracker = TextAreaField("Code de suivi (html)")


class MetaView(MethodView):
    """
    Métadonnées du site
    """
    methods = ('GET', 'POST')

    def get(self):
        form = MetaForm(obj=SiteMetadata())
        return render_template('meta.html', form=form)

    def post(self):
        form = MetaForm(request.form)
        if form.validate():
            meta = SiteMetadata()
            form.populate_obj(meta)
            meta.put()
            current_app.cache.clear()
            flash("Métas enregistrés", 'success')
        return render_template('meta.html', form=form)


mod.add_url_rule('/meta', view_func=MetaView.as_view('meta'))

#######################################################################################################################


class EditForm(Form):
    title = TextField("Titre")
    body = TextAreaField("Corps de texte")


class EditView(MethodView):
    """
    Édition d'une page
    """
    methods = ('GET', 'POST')

    def get(self, slug):
        page = PageMapper().get(slug)
        if page is None:
            abort(404)
        form = EditForm(obj=page)
        return render_template('edit.html', form=form)

    def post(self, slug):
        mapper = PageMapper()
        page = mapper.get(slug)
        if page is None:
            abort(404)
        form = EditForm(request.form)
        if form.validate():
            form.populate_obj(page)
            mapper.put(page)
            current_app.cache.delete(page.slug)
            flash("Page enregistrée", 'success')
            return redirect(url_for('.edit', slug=slug))
        return render_template('edit.html', form=form)


mod.add_url_rule('/edit/<string:slug>', view_func=EditView.as_view('edit'))


@mod.route('/create', methods=('POST',))
def create():
    """
    Création d'une page
    """
    slug = request.form.get('slug', None)
    if not slug:
        flash("Paramètre manquant : slug", 'danger')
        return redirect(url_for('home'))
    mapper = PageMapper()
    page = PageMapper().get(slug)
    if not page:
        page = Page(slug=slug)
        mapper.put(page)
    return redirect(url_for('.edit', slug=slug))


#######################################################################################################################

from werkzeug.utils import secure_filename
from os.path import join


@mod.route('/upload', methods=('POST',))
def upload():
    """
    Téléversement d'image
    Réponse json pour CKEditor
    """
    f = request.files.get('upload')
    fname = secure_filename(f.filename)
    f.save(join(current_app.config['UPLOAD_DIR'], fname))
    return dict(uploaded=True, url=url_for('uploads', filename=fname))

uniphoto/admin/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="theme-color" content="#000000" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <link rel="stylesheet" href="{{ url_for('public_static', filename='css/styles.css') }}">
</head>
<body>
{% if not skip_navigation -%}
<div class="container">
<div class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-start">
    <a class="navbar-item" href="{{ url_for('home') }}">
      Admin
    </a>
  </div>
  <div class="navbar-end">
    <a class="navbar-item" href="{{ url_for('auth.logout') }}">
      Déconnexion
    </a>
  </div>
</div>
</div>
{%- endif %}{# not skip_navigation #}
{% with messages = get_flashed_messages(with_categories=true) -%}
{% if messages -%}
<div class="container">
  {% for category, message in messages -%}
  <div class="notification is-{{ category }}">{{ message }}</div>
  {% endfor -%}
</div>
{% endif -%}
{% endwith -%}

<div class="container">
{% block main %}
{% endblock %}
</div>
</body>
</html>

uniphoto/admin/templates/edit.html
{% extends 'base.html' %}

{% block main %}
<form action="{{ request.path }}" method="POST">

<div class="field">
  <label class="label" for="{{ form.title.id }}">{{ form.title.label }}</label>
  <div class="control">
    <input type="text" class="input" id="{{ form.title.id }}" name="{{ form.title.name }}" value="{{ form.title.data or '' }}" />
  </div>
</div>

<div class="field">
  <label class="label" for="{{ form.body.id }}">{{ form.body.label }}</label>
  <div class="control">
    <textarea id="{{ form.body.id }}" name="{{ form.body.name }}">{{ form.body.data or '' }}</textarea>
  </div>
</div>

<div class="field is-grouped">
  <div class="control">
    <button class="button is-link">Enregistrer</button>
  </div>
</div>

</form>

<script src="{{ url_for('static', filename='ckeditor5/ckeditor.js') }}"></script>
<script>
  ClassicEditor
			.create( document.getElementById("{{ form.body.id }}"), {
				toolbar: {
					items: [
						'heading',
						'|',
						'bold',
						'italic',
						'link',
						'bulletedList',
						'numberedList',
						'|',
            'imageInsert',
						'blockQuote',
						'insertTable',
						'undo',
						'redo'
					]
				},
				language: 'fr',
				image: {
					toolbar: [
            //'linkImage',
            'imageTextAlternative',
            //'imageStyle:full',
            //'imageStyle:side'
					]
				},
				table: {
					contentToolbar: [
						'tableColumn',
						'tableRow',
						'mergeTableCells'
					]
				},
        ckfinder: {
          uploadUrl: "{{ url_for('views.upload') }}",
          withCredentials: true
        },
			} )
			.then( editor => {
				window.editor = editor;
			} )
			.catch( error => {
				console.error(error);
			} );
</script>
{% endblock %}

uniphoto/admin/templates/home.html
{% extends 'base.html' %}

{% block main %}
<h1 class="title">{{ g.meta.title }}</h1>
<label class="label">Pages</label>
<div class="box">
{% if pages %}
<ul>
    {% for slug in pages %}
    <li>
        <a href="{{ url_for('views.edit', slug=slug) }}">{{ slug }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<em>aucune page</em>
{% endif %}
<br/>
<form action="{{ url_for('views.create') }}" method="POST">
    <div class="field is-horizontal">
        <div class="control">
            <input class="input" type="text" name="slug" id="slug"/>
        </div>
        <div class="control">
            <button class="button" type="submit">Créer</button>
        </div>
    </div>
</form>
</div>

<br/>
<label class="label">Maintenance</label>
<a href="{{ url_for('views.meta') }}">Configuration du site</a>
{% endblock %}

uniphoto/admin/templates/login.html
{% extends 'base.html' %}

{% block main %}
<div class="hero is-large">
<div class="hero-body">

<div class="columns">
  <div class="column is-offset-4 is-4">

    <h1 class="title">{{ g.meta.title }}</h1>

    <form action="{{ url_for(request.endpoint) }}" method="POST">
    {% if next -%}
      <input type="hidden" name="next" value="{{ next }}" />
    {%- endif %}

    <div class="field">
      <label class="label">{{ form.username.label }}</label>
      <div class="control">
        <input class="input" type="text" name="{{ form.username.name }}">
      </div>
    </div>

    <div class="field">
      <label class="label">{{ form.password.label }}</label>
      <div class="control">
        <input class="input" type="password" name="{{ form.password.name }}">
      </div>
    </div>

    <br/>

    <div class="field is-grouped">
      <div class="control">
        <button class="button is-link">Connexion</button>
      </div>
    </div>

    </form>

  </div>
</div>{# /columns #}

</div>
</div>{# /hero #}
{% endblock %}

uniphoto/admin/templates/meta.html
{% extends 'base.html' %}

{% block main %}
<form action="{{ url_for(request.endpoint) }}" method="POST">
<div class="field">
    <label class="label" for="{{ form.title.id }}">{{ form.title.label }}</label>
    <div class="control">
        <input class="input" id="{{ form.title.id }}"  name="{{ form.title.name }}" value="{{ form.title.data or '' }}" />
    </div>
</div>

<div class="field">
    <label class="label" for="{{ form.description.id }}">{{ form.description.label }}</label>
    <div class="control">
        <textarea class="textarea" id="{{ form.description.id }}" name="{{ form.description.name }}" rows="4">{{ form.description.data or '' }}</textarea>
    </div>
</div>

<div class="field">
    <label class="label" for="{{ form.header.id }}">{{ form.header.label }}</label>
    <div class="control">
        <textarea class="textarea" id="{{ form.header.id }}" name="{{ form.header.name }}" rows="4">{{ form.header.data or '' }}</textarea>
    </div>
</div>

<div class="field">
    <label class="label" for="{{ form.footer.id }}">{{ form.footer.label }}</label>
    <div class="control">
        <textarea class="textarea" id="{{ form.footer.id }}" name="{{ form.footer.name }}" rows="4">{{ form.footer.data or '' }}</textarea>
    </div>
</div>

<div class="field">
    <label class="label" for="{{ form.tracker.id }}">{{ form.tracker.label }}</label>
    <div class="control">
        <textarea class="textarea" id="{{ form.tracker.id }}" name="{{ form.tracker.name }}" rows="12">{{ form.tracker.data or '' }}</textarea>
    </div>
</div>

<div class="field is-grouped">
  <div class="control">
    <button class="button is-link">Enregistrer</button>
  </div>
</div>
</form>
{% endblock %}